type Query {
	orderStatusInfo: [StatusInfo!]!
	productStatusInfo: [StatusInfo!]!
}

type StatusInfo {
	statusCode: StatusValue!
	statusName: String!
	statusDescription: String!
}

type Status {
	statusCode: StatusValue!
	staff: Staff
	statusChangeTime: DateTime!
	statusInfo: StatusInfo!
}
