type Query {
	transports(
		transportId: ID
		search: String
		productId: ID
		orderId: ID
		staffId: ID
		branchId: [ID!]
		available: Boolean
		sort: TransportSort = {}
		pagination: Pagination = {} 
	): [Transport!]!
}

type Mutation {
	bindOrder(
		transportId: ID!
		orderId: [ID!]
		productId: [ID!]
		type: BindType!
	): MutationResponses!
}

type Transport {
	transportId: ID!
	transportImg: Link!
	transportModel: String!
	transportColor: String!
	transportNumber: String!
	transportSummary: String
	transportBroken: Boolean!
	transportCreatedAt: DateTime!
	driversList: [Driver!]
	driver: Driver
	branch: Branch!
	count: Int
}

type Driver {
	staff: Staff!
	registeredAt: DateTime!
	unRegisteredAt: DateTime
}

input TransportSort {
	transportId: SortOptions
}
