type Query {
	orders(
		orderId: ID
		search: String
		clientId: [ID!]
		branchId: [ID!]
		orderSpecial: Boolean
		orderStatus: [StatusValue!] 
		sort: OrderSort = {}
		pagination: Pagination = {} 
		dateFilter: OrderDateFilter = {}
		addressFilter: AddressFilter = {}
	): [Order!]!
}

type Mutation {
	addOrder(
		clientId: ID
		special: Boolean!
		summary: String
		bringTime: DateTime
		address: AddressInput!
	): MutationResponse!

	changeOrder(
		orderId: ID!
		bringTime: DateTime
		special: Boolean
		summary: String
		address: AddressInput
	): MutationResponse!
}

type Order {
	orderId: ID!
	special: Boolean!
	summary: String
	price: Float
	products: [Product]!
	client: Client!
	branch: Branch!
	address: Address!
	status: Status!
	statusProcess: [Status!]!
	bringTimeRemaining: Second
	deliveryTimeRemaining: Second
	bringTime: DateTime
	broughtTime: DateTime
	deliveryTime: DateTime
	deliveredTime: DateTime
	orderCreatedAt: DateTime!
	count: Int
}

input OrderDateFilter {
	bringTime: RangeDate
	broughtTime: RangeDate
	deliveryTime: RangeDate
	deliveredTime: RangeDate
	orderCreatedAt: RangeDate
}

input OrderSort {
	orderId: SortOptions
	orderStatus: SortOptions
	orderPrice: SortOptions
	firstName: SortOptions
	lastName: SortOptions
	bringTime: SortOptions
	broughtTime: SortOptions
	deliveryTime: SortOptions
	deliveredTime: SortOptions
}