type Query {
	streets(stateId: ID regionId: ID neighborhoodId: ID streetId: ID): [Street!]!
}

type Mutation {
	changeStreet(streetId: ID! neighborhoodId: [ID!] streetName: String streetDistance: Float): MutationResponse!
	addStreet(neighborhoodId: [ID!]! streetName: String! streetDistance: Float!): MutationResponse!
}

type Street {
	streetId: ID!
	streetName: String!
	streetDistance: Float!
	streetCreatedAt: DateTime!
	neighborhoods: [Neighborhood!]!
	region: Region!
	areas: [Area!]!
}