type Query {
	staffs(
		staffId: ID
		userSearch: String
		sort: UserSort = {}
		pagination: Pagination = {} 
		addressFilter: AddressFilter = {}
		userInfoFilter: UserInfoFilter = {}
	): [Staff!]!

	deletedStaffs(
		staffId: ID
		userSearch: String
		sort: UserSort = {}
		pagination: Pagination = {} 
		addressFilter: AddressFilter = {}
		userInfoFilter: UserInfoFilter = {}
	): [Staff!]!
}

type Mutation {
	addStaff(
		mainContact: Contact!
		password: Password!
		branchId: ID!
		file: Upload
		staffSummary: String
		userInfo: UserInfoInput! 
		userAddress: AddressInput!
	): MutationResponse!

	changeStaff(
		staffId: ID!
		password: Password
		branchId: ID
		file: Upload
		staffSummary: String
		userInfo: UserInfoInput = {}
		userAddress: AddressInput = {}
	): MutationResponse!

	deleteStaff(staffId: [ID!]): MutationResponses!
	restoreStaff(staffId: [ID!]): MutationResponses!
	loginStaff(mainContact: Contact! password: Password!): AuthResponse!
}

type Staff {
	satffId: ID!
	count: Int!
	staffImg: Link
	staffSummary: String
	staffInfo: UserInfo!
	staffCreatedAt: DateTime!
}