type Query {
	orderTransactions(
		staffId: [ID] 
		branchId: [ID]
		orderId: [ID]
		moneyAmount: Int
		transactionId: ID
		dateFilter: RangeDate
		pagination: Pagination = {}
		transactionType: TransactionType!
	): [OrderTransaction!]!
}

type Mutation {
	makeOrderTransaction(
		transactionType: TransactionType!
		orderId: ID!
		transactionMoneyCash: Int = 0
		transactionMoneyCard: Int = 0
		transactionSummary: String
	): MutationResponse!

	changeOrderTransaction(
		transactionId: ID! 
		transactionSummary: String
		transactionMoneyCash: Int = 0
		transactionMoneyCard: Int = 0
	): MutationResponse!
	
	deleteOrderTransaction(transactionId: ID!): MutationResponse!
}

type OrderTransaction {
	staff: Staff!
	order: Order!
	branch: Branch!
	transactionId: ID!
	transactionMoneyCash: Int!
	transactionMoneyCard: Int!
	transactionMoneyTotal: Int!
	transactionSummary: String
	transactionCreatedAt: DateTime!
	transactionType: TransactionType!
	transactionStatus: TransactionStatus!
	count: Int!
}

enum TransactionType {
	income
	outcome
}

enum TransactionStatus {
	pending
	accepted
	cancelled
	deleted
	active
}
