type Query {
	expanseTransactions(
		expanseId: ID
		branchId: [ID]
		moneyAmount: Int
		transactionId: ID
		transactionTo: ID
		transactionFrom: ID
		moneyType: MoneyType
		dateFilter: RangeDate
		pagination: Pagination = {}
		transactionType: TransactionType!
		transactionStatus: TransactionStatus
	): [ExpanseTransaction!]!

	expanses: [Expanse]!
}

type Mutation {
	makeExpanseTransaction(
		expanseId: ID!
		transactionTo: ID!
		transactionFrom: ID!
		transactionMoney: Int! = 0
		transactionSummary: String
		transactionDateTime: DateTime
		transactionMoneyType: MoneyType!
	): MutationResponse!

	changeExpanseTransaction(
		transactionId: ID!
		expanseId: ID
		transactionTo: ID
		transactionFrom: ID
		transactionMoney: Int = 0
		transactionSummary: String
		transactionDateTime: DateTime
		transactionMoneyType: MoneyType
	): MutationResponse!

	acceptExpanseTransaction(transactionId: ID!): MutationResponse!
	cancelExpanseTransaction(transactionId: ID!): MutationResponse!
	deleteExpanseTransaction(transactionId: ID!): MutationResponse!

	addExpanse(expanseName: String): MutationResponse!
	deleteExpanse(expanseId: ID!): MutationResponse!
}

type ExpanseTransaction {
	branch: Branch!
	expanse: Expanse!
	transactionId: ID!
	transactionTo: Staff!
	transactionFrom: Staff!
	transactionMoney: Int!
	transactionSummary: String
	transactionCreatedAt: DateTime!
	transactionMoneyType: MoneyType!
	transactionType: TransactionType!
	transactionStatus: TransactionStatus!
	count: Int!
}

type Expanse {
	expanseId: ID!
	expanseName: String!
	expanseCreatedAt: DateTime!
}