type Query {
	areas(regionId: ID! neighborhoodId: ID streetId: ID areaId: ID): [Area!]!
}

type Mutation {
	addArea(streetId: [ID!]! areaName: String! areaDistance: Float!): MutationResponse!
	changeArea(areaId: ID! streetId: [ID!] areaName: String areaDistance: Float): MutationResponse!
}

type Area {
	areaId: ID!
	areaName: String!
	areaDistance: Float!
	areaCreatedAt: Date!
	streets: [Street!]!
	neighborhood: Neighborhood!
}