type Query {
	services(serviceId: ID branchId: [ID!]): [Service!]!
	disabledServices(serviceId: ID branchId: [ID!]): [Service!]!

	deliveryHours(branchId: [ID!]): [DeliveryHour!]!
}

type Mutation {
	addService(
		branchId: ID!
		serviceName: String!
		serviceUnit: String!
		serviceUnitKeys: [String!] = ["qiymat"]
		servicePriceSpecial: Float!
		servicePriceSimple: Float!
	): MutationResponse!

	changeService(
		serviceId: ID!
		branchId: ID
		serviceName: String
		serviceUnit: String
		serviceUnitKeys: [String!]
		servicePriceSpecial: Float
		servicePriceSimple: Float
	): MutationResponse!

	disableService(serviceId: [ID!]!): MutationResponses!
	enableService(serviceId: [ID!]!): MutationResponses!

	changeDeliveryHour(deliveryHourId: ID! deliveryHourSpecial: Int deliveryHourSimple: Int): MutationResponse!
}

type Service {
	serviceId: ID!
	serviceName: String!
	serviceUnit: String!
	serviceUnitKeys: [String!]!
	servicePriceSpecial: Float!
	servicePriceSimple: Float!
	serviceCreatedAt: DateTime!
	branch: Branch!
}

type DeliveryHour {
	deliveryHourId: ID!
	deliveryHourSpecial: Second!
	deliveryHourSimple: Second!
	branch: Branch!
	deliveryHourCreatedAt: DateTime!
}
