type Query {
	productsKPI(
		staffId: ID!
		branchId: ID!
		statusCode: StatusValue!
		dateFilter: RangeDate = {}
	): ProductsKPI!

	productStatusesKPI(
		staffId: [ID!]
		branchId: [ID!]
		productId: ID
		dateFilter: RangeDate = {}
		pagination: Pagination = {} 
	): [ProductStatusesKPI!]!
}

type ProductsKPI {
	totalProducts: Int!
	services: [ProductServiceKPI!]! 
}

type ProductServiceKPI {
	service: Service!
	amount: Int!
}

type ProductStatusesKPI {
	statusFrom: StatusInfo!
	statusTo: StatusInfo!
	createdAt: DateTime!
	pruductId: Int!
	staff: Staff!
}