# scalars that have type check
scalar Date


# simple scalars that do not have type check
scalar Any


# unions
union BigTypes = Branch | State | Region | Neighborhood | Street | Area


# types
type MutationResponse {
	status: Any!
	message: String!
	data: BigTypes
}

type MutationResponses {
	status: Any!
	message: String!
	data: [BigTypes!]
}
