# scalars that have type check
scalar Upload
scalar DateTime
scalar Date
scalar ID
scalar SVG
scalar Contact
scalar Password

# simple scalars that do not have type check
scalar Any
scalar Link


# unions
union BigTypes = Branch | State | Region | Neighborhood | Street | Area | SocialSet | Client | Staff


#enums
enum Gender {
	male
	female
}

enum SortOptions {
	toSmallest
	toLargest
}

# inputs
input Dual {
	from: Int = 0
	to: Int = 0
}

input Pagination {
	limit: Int = 300
	page: Int = 1
}

# types
type MutationResponse {
	status: Any!
	message: String!
	data: BigTypes
}

type MutationResponses {
	status: Any!
	message: String!
	data: [BigTypes!]
}
